apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# These will be replaced by the deploy script
nameSuffix: ""

# Patches applied per-PR
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "0"
    target:
      kind: Deployment
      name: preview-app
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "unknown"
    target:
      kind: Deployment
      name: preview-app

# Image will be set dynamically
images:
  - name: preview-app
    newName: preview-app
    newTag: latest
